#include=~~/hdr-toys.conf
profile=gpu-hq
display-tags=
cache=yes
demuxer-max-bytes=2G
demuxer-max-back-bytes=128M
demuxer-readahead-secs=30
cache-secs=30
cache-on-disk=no
cache-pause=no
cache-pause-wait=3
demuxer-mkv-probe-video-duration=no
### Dynamic crop
#script-opts-append=dynamic_crop-mode=4
script-opts-append=dynamic_crop-read_ahead_mode=1
script-opts-append=dynamic_crop-limit_timer=0.1
#vo=gpu
#gpu-context=waylandvk
#hdr-compute-peak=yes
#tone-mapping=auto
hwdec=nvdec-copy
#gpu-api=vulkan
target-colorspace-hint=yes
tone-mapping=clip
gamut-mapping-mode=clip
### HDR → SDR (use bt.2390 ONLY here) ###
[tm-bt2390]
profile-cond=get("video-params/primaries") == "bt.2020" and get("target-prim") ~= "bt.2020"
tone-mapping=bt.2390
hdr-compute-peak=no
### SDR (no tone mapping at all) ###
[sdr-native]
profile-cond=get("video-params/primaries") ~= "bt.2020"
tone-mapping=clip
#target-colorspace-hdr=auto
#target-colorspace-hint=yes
scale-antiring=0.6
dscale-antiring=0.6
cscale-antiring=0.6
#video-sync=display-resample
video-sync=display-vdrop
temporal-dither=yes
### Debanding (off unless needed) ###
deband=no
deband-iterations=1
deband-threshold=48
deband-range=16
deband-grain=32
### Audio & Subtitles ###
slang=ar,ara,Arabic,en,eng
alang=ja,jpn,jap,Japanese,en,eng,English
sub-blur=0.35
sub-bold=yes
sub-scale=0.85
sub-margin-y=25
sub-font='Calibri'
sub-font-size=30
sub-codepage=cp1256
sub-shadow-offset=0.4
sub-border-size=0.85
sub-auto=all
sub-ass-override=force
blend-subtitles=yes
audio-channels=2
ao=pulse
volume-max=100
sub-fix-timing=yes
audio-file-auto=fuzzy
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=sub;subs;subtitles
### General ###
fs=yes
snap-window
keep-open=always
geometry=50%:50%
save-position-on-quit=yes
watch-later-options-remove=pause
hr-seek=no
### OSD ###
osc=no
border=no
osd-bar=no
osd-bold=yes
osd-font-size=37
osd-font=calibri
### Screenshots ###
screenshot-template="/home/btw/Pictures/mpv/%F [%wH.%wM.%wS.%wT]"
screenshot-format=png
screenshot-tag-colorspace=yes
screenshot-png-compression=5
### Terminal ###
msg-color=yes
msg-module=yes
msg-level=auto_profiles=no
msg-level=ytdl_hook=no,ffmpeg=no
msg-level=all=warn,dynamic_crop=info
msg-level=thumbfast=error
msg-level=ffmpeg=no
