# The url of your server
# ex. https://jellyfin.example.com
# or http://192.168.1.40:8096/jellyfin
url=https://001.emy.mx/

# Just your username
# ex. btw
username=16T88YR1P

# Just your password, matching the username
# ex. pass123
password=Semo1419

# The system path to store images
# ex. /tmp/mpv-jellyfin
# or /home/btw/.cache/mpv-jellyfin
image_path=/home/btw/.cache/mpv-jellyfin

# Should descriptions be hidden if the item hasn't been watched yet
# Defaults to on
# ex. off
hide_spoilers=

# Show the script's UI at start
# Defaults to off
# ex. on
show_by_default=
